package ru.softshaper.drools.service;
import ru.softshaper.services.drools.bean.*;
import ru.softshaper.services.drools.parser.*;
import ru.softshaper.services.drools.contex.RuleContext;
global Parser parser
rule "parseData"
salience 10
when 
$ruleContext :  RuleContext( mode == "parse" )
then
	Data data = $ruleContext.getData();
    if(data!=null){
        MetaData metaData = parser.parse(data);    
		$ruleContext.setMetaData(metaData);
		$ruleContext.setMode("save");
		System.out.println(metaData);
		update($ruleContext);
	}
	System.out.println("end rule parseData");
	
end