package ru.softshaper.drools.service;
import ru.softshaper.services.drools.bean.*;
import ru.softshaper.services.drools.saver.*;
import ru.softshaper.services.drools.contex.RuleContext;

global Saver saver
rule "saveData"
salience 20
when 
$ruleContext :  RuleContext( mode == "save" )
then
	Data data = $ruleContext.getData();
	MetaData metaData = $ruleContext.getMetaData();
    if(data!=null && metaData!=null){
        saver.save(data,metaData);    
        $ruleContext.setMode("end");
		System.out.println($ruleContext);
		insert($ruleContext);
	}
	System.out.println("end rule saveData");

end